export const TYPES = {
  ILogger: Symbol('ILogger'),
  IConfigurationValidationSchema: Symbol('IConfigurationValidationSchema'),
  IConfiguration: Symbol('IConfiguration'),
  IChainIdScrapper: Symbol('IChainIdScrapper'),
  IChainRpcScrapper: Symbol('IChainRpcScrapper'),
  IChainConfigurationScrapper: Symbol('IChainConfigurationScrapper'),
  IProviderConfigurationMerger: Symbol('IProviderConfigurationMerger'),
  INodeStorageRepository: Symbol('INodeStorageRepository'),
  IProvider: Symbol('IProvider'),
  IKafkaClient: Symbol('IKafkaClient'),
  IConsumerInstance: Symbol('IConsumerInstance'),
  ICommitManager: Symbol('ICommitManager'),
  IRedisClient: Symbol('IRedisClient'),
};
